issues/urls.py
from django.conf.urls import *
from django.contrib.auth.decorators import login_required as LR
from .models import *
from .views import *
urlpatterns = patterns('',
    url(r"^profile/(?P<pk>\d+)/$", LR(EditProfile.as_view()), name="profile"),
    url(r"^viewprofile/(?P<pk>\d+)/$" , LR(UserPageView.as_view()), name="viewprofile"),
    url(r"^forum/(?P<dpk>\d+)/$", LR(ForumView.as_view()), name= "forum"),
    url(r"^topic/(?P<dpk>\d+)/$", LR(TopicView.as_view()), name= "topic"),
    url(r"^forums$", LR(ForumList.as_view()), name="forums"),
    url(r"^$", Main.as_view(), name="main"),
)

project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^issues/', include('issues.urls', namespace="issues")),
    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/', include('allauth.urls')),
)

issues/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.contrib import admin
from django.db.models.signals import post_save
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.dispatch import receiver

# Create your models here.
#==========================================================================================
class Skill(models.Model):
    skillName = models.CharField(max_length=200)
    def __str__(self):
        return self.skillName
#==========================================================================================
class Project(models.Model):
    ProjectName= models.CharField(max_length=200)
    projectDescription = models.TextField(max_length=2000)
    projectAccessType=models.BooleanField(default=True)
    owner = models.ForeignKey(User, related_name="owner")
    def __str__(self):
        return self.ProjectName
#==========================================================================================
class Task(models.Model):
    taskTitle = models.CharField(max_length=200)
    taskDescription = models.TextField(max_length=2000)
    skills = models.ManyToManyField(Skill,"taskSkills")
    project=models.ForeignKey(Project,related_name="project")
    operator = models.ManyToManyField(User,related_name="operator")
    def __str__(self):
        return self.taskTitle
#==========================================================================================
class UserProfile(models.Model):
    #avatar = models.URLField(null=True)
    state = models.BooleanField(default=True)
    #fieldOfStudy = models.CharField(max_length=200)
    #university = models.CharField(max_length=200)
    #cityState = models.CharField(max_length=100)
    #city = models.CharField(max_length=100)
    #grade = models.IntegerField(default=0)
    user = models.OneToOneField(User, related_name="profile")
    #skills = models.ManyToManyField(Skill,related_name="userSkills",null=True)
    #tasks = models.ManyToManyField (Task,related_name="userTasks",null=True)
    @models.permalink
    def get_absolute_url(self):
        return ('issues:viewprofile', None,{'pk':self.user.pk})
    def __str__(self):
        return self.user.username
def user_post_save(sender, instance, created, **kwargs):
    """Create a user profile when a new user account is created"""
    if created == True:
        p = UserProfile()
        p.user = instance
        p.save()

post_save.connect(user_post_save, sender=User)

#==========================================================================================
class Forum(models.Model):

    title = models.CharField(max_length=60)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
       """ it gets the absolute url of current forum page , this method has been used in views"""
       return str("issues:forum",args=[self.pk])

    def numPosts(self):
        """returns the total number of  the posts in each forum"""
        return sum([t.numPosts() for t in self.topics.all()])

    def lastPost(self):
        """finds the last post of all the topics in a forum"""
        topics = self.topics.all()# the list of topics in a forum
        last    = None
        for topic in topics:#like finding the maximum of a list
            templastp = topic.lastPost()
            if templastp and (not last or templastp.date > last.date):
                last = templastp
        return last

#==========================================================================================
class Topic(models.Model):
    title   = models.CharField(max_length=60)
    date = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, blank=True, null=True)
    forum   = models.ForeignKey(Forum, related_name="topics")

    class Meta:
        ordering = ["-date"]# order topics by their date of creation

    def __str__(self):
        return str("%s - %s" % (self.creator, self.title))

    def get_absolute_url(self) :
        """ it gets the absolute url of current topic page, this method has been used in views"""
        return str("issues:topic", args=[self.pk])

    def lastPost(self)  :
        """returns the most recent post of the topic"""
        return self.posts.all()[0]#the first post is the recent post

    def numPosts(self) :
        """returns the number of  the posts in each topic"""
        return self.posts.count()

    def numReplies(self) :
        """returns the number of the replies in each topic"""
        return self.posts.count() - 1#because the first post isn't a reply

#==========================================================================================
class Post(models.Model):
    title = models.CharField(max_length=60)
    date = models.DateTimeField(auto_now_add=True)
    creator=models.ForeignKey(User, blank=True, null=True)
    topic = models.ForeignKey(Topic, related_name="posts")
    body = models.TextField(max_length=10000)

    class Meta:
        ordering = ["date"]

    def __str__(self):
        return u"%s - %s - %s" % (self.creator, self.topic, self.title)

    def short(self):
        """this method is used in lastposts column to show creator and title and date"""
        date = self.date.strftime("%b %d, %I:%M %p")
        return u"%s - %s\n%s" % (self.creator, self.title, date)

    def profileData(self):
        """this method is used in each post to see the creator's avatar and number of his posts"""
        p = self.creator.profile
        return p.posts

issues/forms.py
from django.forms import ModelForm
from issues.models import *
class ProfileForm(ModelForm):
    class Meta:
        model  = UserProfile
        exclude = ["grade", "user"]
class PostForm( ModelForm):
    """post form class which contains all the fields except creator and topic fields."""
    class Meta:
        model = Post
        exclude = ["creator", "topic"]

issues/views.py
from django.shortcuts import render

# Create your views here.
from .models import *
from django.views import generic
from .forms import *
from django.shortcuts import redirect
from django.conf import settings
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout
from django.contrib.messages.api import get_messages
class Main(generic.ListView):
    """desplays list of forums names and their last post."""
    model = Project
    def get_context_data(self, **kwargs):
        context = super(Main, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context
    template_name = "main.html"
class UserPageView(generic.DetailView):
    model = UserProfile
    template_name = "userpage.html"

class EditProfile(generic.UpdateView):
    model = UserProfile
    fields = ['state']
    template_name_suffix = '_update_form'

class ForumList(generic.ListView):
    """desplays list of forums names and their last post."""
    list_model = Forum
    model = Forum
    template_name = "list.html"

class ForumView(generic.ListView):#(listview+detailview)
    """desplays all of the topics in each forum"""
    list_model = Topic
    model = Topic
    related_name = "topics"
    template_name = "forum.html"

class TopicView(generic.ListView):
    """desplays all of the posts in each topic"""
    list_model = Post
    detail_model = Topic
    model = Post
    related_name  = "posts"
    template_name = "topic.html"

issues/templates/base.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}ISSUES{% endblock %}</title>

    <style type="text/css">
        * {
            font-family:"Comic Sans MS", cursive, sans-serif;
            color: #555;
            font-size: 0.98em;
            word-wrap:break-word;
        }
        #menu a {
            font-family:"Comic Sans MS", cursive, sans-serif;
            text-decoration: none;
            background: #a6a6a6;
            border-top: 1px solid #ccc;
            border-bottom: 1px solid #ccc;
            border-right: 2px solid #fff;
            padding-right: 3px;
            padding-left: 3px;
            color: white;
            font-size: 1em;
        }
        a:hover {
            font-family:"Comic Sans MS", cursive, sans-serif;
            background: #eeebeb;
            border-top: 1px solid #aaa;
            border-bottom: 1px solid #aaa;
            color: #555;
        }
        body {
        background-color: white;}
        #container { margin: auto; width: 700px; border: 0px solid; }
        p { font-family:"Comic Sans MS", cursive, sans-serif;font-size: 1.1em;background:white; }
        h3 { margin-right: 30px; display: inline; }
    </style>

</head>

<body>
    <div id="sidebar"> {% block sidebar %} {% endblock %} </div>
    <div id="container">
        <div id="menu">
            {% block nav-global %}

                <!-- MENU -->
            {% load staticfiles %}
            {% if user.is_staff %} <a href="{% url 'admin:index' %}">Admin</a> {% endif %}
                {% if user.is_authenticated %}
                    <a href="{% url 'issues:main' %}">Main</a>
                    <a href="{% url 'issues:profile' user.pk %}">Edit profile</a>
                    <a href="{% url 'issues:viewprofile' user.pk %}">My Page</a>
                    <a href="{% url 'issues:forums'%}">Forum</a> {% endif %}
                {% if not user.is_authenticated %}<a href="/accounts/login/?next=/issues/">login</a> | <a
                    href="/accounts/signup/">register</a>{% endif %}

                {% if user.is_authenticated %}<a href="/accounts/logout/?next=/issues/">logout</a>
                    {% endif %}

            {% endblock %}
        </div>

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

issues/templates/forum.html
{% extends "base.html" %}
{% if user.is_staff %} <a href="{% url 'admin:index' %}">Admin</a> {% endif %}
                {% if user.is_authenticated %}
                    <a href="{% url 'issues:main' %}">Main</a>
                    <a href="{% url 'issues:profile' user.pk %}">Edit profile</a>
                    <a href="{% url 'issues:viewprofile' user.pk %}">My Page</a>
                    <a href="{% url 'issues:forums' %}">Forum</a>
                {% endif %}

                {% if not user.is_authenticated %}<a href="/accounts/login/?next=/issues/">login</a> {% endif %}

                {% if user.is_authenticated %}<a href="/accounts/logout/?next=/issues/">logout</a>{% endif %}
{% block content %}
    <style type="text/css">
        .pagination { margin-top: 20px; margin-left: -20px; }
        .main { margin-left: 25px; margin-top: 30px; width: 700px; }
        .title { font-size: 1.4em; margin-top: 0px; padding-left: 4px; }
        .last { border: 0px; }
        .title a { text-decoration: none; }
        .button { background: #999; color: white; padding: 4px; text-decoration: none; }
        .buttont { background: #999; color: white; padding: 2px; text-decoration: none; }
        td { border-bottom: 1px solid #ccc; }
        #list { border: 1px solid #ccc; width: 700px;background:white; }
        #new_topic { float: right; }
    </style>

    <div class="main">

      <div id="list">
          {% if topic_list %}
            <table border="0" cellpadding="4" width="100%">
                <tr>
                    <td>Topics</td>
                    <td>Replies</td>
                    <td>Last post</td>
                    <td></td>
                </tr>

                <!-- Topics  -->
                {% for topic in topic_list %}
                <tr {% if forloop.last %}class="last"{% endif %}>
                    <td>
                        <div class="title"> <a href="{% url 'issues:topic' topic.pk %}">{{ topic.title }}</a></div>
                    </td>
                    <td>{{ topic.numReplies }}</td>
                    <td>{{ topic.lastPost.short|linebreaksbr }}</td>
                    <td><a class="button" href="{% url 'issues:topic' topic.pk %}">VIEW</a></td>
                </tr>

                {% endfor %}
            </table>
        {% else %}
          <blockquote>No topics in this forum yet..</blockquote>
        {% endif %}
        </div>
        {% include "pagination.html" %}
        </div>
{% endblock %}

issues/templates/issues/userprofile_update_form.html
{% extends "base.html" %}
{% if user.is_staff %} <a href="{% url 'admin:index' %}">Admin</a> {% endif %}
                {% if user.is_authenticated %}
                    <a href="{% url 'issues:main' %}">Main</a>
                    <a href="{% url 'issues:profile' user.pk %}">Edit profile</a>
                    <a href="{% url 'issues:viewprofile' user.pk %}">My Page</a>
                    <a href="{% url 'issues:forums' %}">Forum</a>
                {% endif %}

                {% if not user.is_authenticated %}<a href="/accounts/login/?next=/issues/">login</a> | <a
                    href="/accounts/register/">register</a>
                {% endif %}

                {% if user.is_authenticated %}<a href="/accounts/logout/?next=/issues/">logout</a>{% endif %}
{% block content %}
{% block sidebar %} <style type="text/css"> </style> {% endblock %}

    <style type="text/css">
        .main { margin-left: 25px; margin-top: 30px; }
        #submit { float:inherit;}
    </style>

    <div class="main">

    <p>
     <form action="" method="post" >{% csrf_token %}
           <table>
                {{form.as_table }}
            </table>
            <input type="submit" value="Update" />
        </form>
    </p>
</div>

{% endblock %}

issues/templates/list.html
{% extends "base.html" %}
{% if user.is_authenticated %}
                    <a href="{% url 'issues:main' %}">Main</a>
                    <a href="{% url 'issues:profile' user.pk %}">Edit profile</a>
                    <a href="{% url 'issues:viewprofile' user.pk %}">My Page</a>
                    <a href="{% url 'issues:forums' %}">Forum</a>
                {% endif %}

                {% if not user.is_authenticated %}<a href="/accounts/login/?next=/issues/">login</a> {% endif %}

                {% if user.is_authenticated %}<a href="/accounts/logout/?next=/issues/">logout</a>{% endif %}
{% block content %}
    <style type="text/css">
        .main { margin-left: 25px; margin-top: 30px;background:white;}
        .title { font-size: 1.4em; margin-top: 10px; border-bottom: 0px solid #ccc; padding-left: 4px;background:white; }
        .last { border: 0px; }
        .title a { text-decoration: none; }
        .button { background: #999; color: white; padding: 4px; text-decoration: none; }
        td { border-bottom: 1px solid #ccc; }
        #list { border: 1px solid #ccc; width: 700px;background:white; }
    </style>

    <div class="main">

        <div id="list">
        <table border="0" cellpadding="4" width="100%">
            <tr>
                <td></td>
                <td>Posts</td>
                <td>Last post</td>
                <td></td>
            </tr>

            <!-- Forums  -->
            {% for forum in forum_list %}
            <tr{% if forloop.last %}class="last"{% endif %}>
                <td>
                    <div class="title"> <a href="{% url 'issues:forum' dpk=forum.pk %}">{{ forum.title }}</a></div>

                </td>
                <td>{{ forum.numPosts }}</td>
                <td>{{ forum.lastPost.short|linebreaksbr }}</td>
                <td><a class="button" href="{% url 'issues:forum' dpk=forum.pk %}">VIEW</a></td>
            </tr>

            {% endfor %}
            </table>
        </div>

    </div>

{% endblock %}

issues/templates/main.html
{% extends "base.html" %}

{% block sidebar %} <style type="text/css"> </style> {% endblock %}

{% block content %}
    <style type="text/css">
        .main { margin-left: 25px; margin-top: 30px;background:white;}
        .title { font-size: 1.4em; margin-top: 10px; border-bottom: 0px solid #ccc; padding-left: 4px;background:white; }
        .last { border: 0px; }
        .title a { text-decoration: none; }
        .button { background: #999; color: white; padding: 4px; text-decoration: none; }
        td { border-bottom: 1px solid #ccc; }
        #list { border: 1px solid #ccc; width: 700px;background:white; }
    </style>

    <div class="main">

        {% if user.is_authenticated %}
            <div id="list">
            <table border="0" cellpadding="4" width="100%">
                <tr>
                    <td></td>
                    <td>Title</td>
                    <td>Date</td>
                    <td>Owner</td>
                    <td>Description</td>
                    <td></td>
                </tr>
                {% for p in object_list%}
                <tr>{% if forloop.last %}class="last"{% endif %}
                    <td>
                        <div class="title"> <a >{{ p.projectname }}</a></div>

                    </td>
                    <td>{{ p.projectstartdate }}</td>
                    <td>{{ p.owner}}</td>
                    <td>{{ p.projectDescription |linebreaksbr }}</td>

                    <td><a class="button">VIEW</a></td>
                </tr>
                {% endfor %}
             {%endif%}
            </div>
    </div>
{% endblock %}

issues/templates/pagination.html
{% load admin_list %}
{% load i18n %}
<p class="paginator">
{% if pagination_required %}
{% for i in page_range %}
    {% paginator_number cl i %}
{% endfor %}
{% endif %}
{{ cl.result_count }} {% ifequal cl.result_count 1 %}{{ cl.opts.verbose_name }}{% else %}{{ cl.opts.verbose_name_plural }}{% endifequal %}
{% if show_all_url %}&nbsp;&nbsp;<a href="{{ show_all_url }}" class="showall">{% trans 'Show all' %}</a>{% endif %}
{% if cl.formset and cl.result_count %}<input type="submit" name="_save" class="default" value="{% trans 'Save' %}"/>{% endif %}
</p>

issues/templates/post.html
{% extends "base.html" %}
{% block sidebar %} <style type="text/css"> </style> {% endblock %}

{% block content %}
    <style type="text/css">
        .main { margin-left: 25px; margin-top: 30px; }
        .last { border: 0px; }
        #reply { margin-top: 10px; width: 500px; }
        #body { width: 500px; height: 250px; font-size: 1.3em; }
        #submit { float: right; }
        #rtitle {
            background: #eee; font-size: 1.3em; padding: 3px; margin-top: 40px;
            padding-left: 20px; margin-bottom: -10px;
        }
    </style>

    <div class="main">
        <div id="reply">
        <form action="" method="POST"> {% csrf_token %}
            <table>
                {{ modelform.as_table }}
            </table>
            <input type="submit" value="Submit" />
        </form>
        </div>
    </div>

issues/templates/topic.html
{% extends "base.html" %}

{% block sidebar %}
<style type="text/css"> </style> {% endblock %}

{% block content %}
    <style type="text/css">
        .pagination { margin-top: 20px; margin-left: -20px; }
        .main { margin-left: 25px; margin-top: 30px; width: 700px; }
        .title { font-size: 1.4em; margin-top: 10px; padding-left: 0px; }
        .title a { text-decoration: none; }
        .button { background: #999; color: white; padding: 6px; text-decoration: none; float: right; }
        .date { font-size: 0.8em; padding-left: 5px; }
        .ppic { float: right;margin: 8px; padding: 8px; margin-bottom: 14px; background: white; }
        .clear { clear: both; }
        #reply { margin-top: 10px; width: 500px; }
        .post {
            margin: 1px; padding: 1px; border: 1px solid #ccc; margin-bottom: 1px; background: white;
            }
        .ttitle {
            font-style: bold; font-size: 1.6em; border-bottom: 1px solid #ccc; margin-bottom: 9px;
            padding-left: 10px; width: 700px;
        }
        #list { border: 1px solid #ccc; width: 700px;background:white; }
        #back { margin: 5px; }
    </style>

<div class="main">

    <!-- Title and backlink -->

    <div class="ttitle">{{ topic.title }}</div>
    <div id="back">
        <a>&lt;&lt; back to list of topics</a>
    </div>


    <!-- Posts  -->

    <div id="list">
        {% for post in post_list %}
            <div class="post">

                <!-- Profile pic and info -->

                <div class="ppic">
                    <img src="{{ media_url }}{{ post.creator.profile.avatar }}" /> <br />
                    {{ post.creator }}<br />
                    Joined: {{ post.creator.date_joined|date:"M d Y" }}

                </div>

                <!-- Title, author and body -->

                <span class="title">{{ post.title }}</span><br />
                by {{ post.creator }} | <span class="date">{{ post.created }}</span> <br /><br />

                {{ post.body|linebreaksbr }} <br />
                <div class="clear"></div>

            </div>
        {% endfor %}
    </div>

    <!-- Paginator and reply link -->

    {% include "pagination.html" %}
    <br />

</div>
{% endblock %}

issues/templates/userpage.html
{% extends "base.html" %}
{%block content%}
<center>
                    <div class="ppic"><img src="{{ userprofile.avatar }}"  alt="No Profile picture" height="200" width="200"/><br /></div>
            <br />
                    <div class="title">Name:</div>
                    <div class="detail"> {{ user.first_name}}<br /></div>
                    <div class="title">city:</div>
                    <div class="detail"> {{ userprofile.city}}<br /></div>
                    <div class="title">Email Address:</div>
                    <div class="detail">{{ userprofile.user.email }}<br /></div>
                    <div class="title">grades:</div>
                    <div class="detail">{{ userprofile.grades }}<br /></div>
                    <div class="title">state:</div>
                    <div class="detail">{{ userprofile.state }}<br /></div>
                    <div class="title">fielsofstudy:</div>
                    <div class="detail">{{ userprofile.fieldOfStudy|linebreaksbr }}<br /></div>
                    <div class="title">Last Login:</div>
                    <div class="detail">{{ userprofile.user.last_login|date:"M d Y" }}<br /></div>
                    <div class="title">Joined: </div>
</center>
{%endblock%}